### ISSUE TITLE
okta-cli users add fails with api error: E0000003

### ISSUE THREAD

**Issue by anotherbhav** [flypenguin/okta-cli#1]
When I run the following:
`okta-cli users add --set "login=myemail@example.com" --set "email=myemail@example.com" --set "firstName=First" --set "lastName=Last"`

I get the following error:
`ERROR: {"errorCode": "E0000003", "errorSummary": "The request body was not well-formed.", "errorLink": "E0000003", "errorId": "oaewUnkGrYhRWWZKWIxxxx", "errorCauses": []}`

This fixes it:
in okta.py
if I add the following line: `body_object = { 'profile': body_object }` then add_user succeeds.

like so
```
    def add_user(self, query_params, body_object):
        body_object = { 'profile': body_object }
        body = json.dumps(body_object).encode("utf-8")
```

then I get a success from the API:
```
  "status": "PROVISIONED",
```

Would you like me to create a pull request?

**Comment by flypenguin** [comment]
hi @anotherbhav , this is not a bug - it's a feature :) . I did push a new release with a couple of changes to `users add`:

- remove `-r CSV`
- change `-p` semantics
- updated documentation with examples and clarifications

As for the "it's not a bug" part: `-s` sets a field [in the request's `user` object](https://is.gd/MuKJga), and _not_ [in the `profile` "sub"-object](https://developer.okta.com/docs/reference/api/users/#profile-object). So the "correct" way of writing your command would have been this: `okta-cli users add -s profile.login="myemail@example.com"` (notice the `profile.` prefix?)

This is still the same, but I re-used the `-p` flag to become a shortcut, so `-s profile.login=LOGIN` is now the same as  `-p login=LOGIN`.

But I fully understand, the docs were missing and this should have been more clear. I hope it is now. v10.0.0 should be up, I'd appreciate feedback if it's not working as expected.
