### ISSUE TITLE
Python 3.10.5 Issue

### ISSUE THREAD

**Issue by tanng1999** [flypenguin/okta-cli#11]
I tried to upgrade my Python version to 3.10.5 and get the following error when running `okta-cli list`.

`class DottedList(DottedCollection, collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'`

Does anyone know if Okta-cli can support Python version 3.10.x?  Thanks.

**Comment by flypenguin** [comment]
@tanng1999 fix is merged, will release a new version now. feedback appreciated whether it works or not! :)

**Comment by flypenguin** [comment]
v17.3.2 is out on pypi, i might have skipped v17.3.1.

**Comment by flypenguin** [comment]
hm, closing this being optimistic it works. if not, please re-open.

**Comment by tanng1999** [comment]
@flypenguin Tried to upgrade to okta-cli 17.3.2 using Python 3.10.6.  Got this error message.

AttributeError: module 'collections' has no attribute 'MutableSequence'

Saw this URL with more info.
https://stackoverflow.com/questions/70284852/couldnt-run-the-py-file-attributeerror-module-collections-has-no-attribut
