### ISSUE TITLE
Inline dotted is missing from pip installed package.

### ISSUE THREAD

**Issue by sanitybit** [flypenguin/okta-cli#13]
First, thank you so much for creating and maintaining this utility.

I upgraded from a working pip install of `17.3.2` to a pip install of `18.0.0` using `pip install --upgrade okta-cli`.

After upgrading, running `okta-cli` returns the following Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/okta-cli", line 5, in <module>
    from oktacli import cli_main
  File "/usr/local/lib/python3.10/site-packages/oktacli/__init__.py", line 1, in <module>
    from .cli import cli_main
  File "/usr/local/lib/python3.10/site-packages/oktacli/cli.py", line 17, in <module>
    from .dotted.collection import DottedDict, DottedCollection
ModuleNotFoundError: No module named 'oktacli.dotted'
```

Looking at the site-package path, I saw that the dotted folder present in the repository is missing:

```
ls -lah /usr/local/lib/python3.10/site-packages/oktacli

-rw-r--r--    1 daniel.huckmann  admin    26B Jan 31 15:58 __init__.py
-rw-r--r--    1 daniel.huckmann  admin    70B Jan 31 15:58 __main__.py
drwxr-xr-x    9 daniel.huckmann  admin   288B Jan 31 16:08 __pycache__
-rw-r--r--    1 daniel.huckmann  admin   2.9K Jan 31 15:58 api.py
-rw-r--r--    1 daniel.huckmann  admin    65K Jan 31 16:08 cli.py
-rw-r--r--    1 daniel.huckmann  admin   129B Jan 31 15:58 exceptions.py
-rw-r--r--    1 daniel.huckmann  admin   7.5K Jan 31 15:58 okta.py
-rw-r--r--    1 daniel.huckmann  admin   610B Jan 31 15:58 pwgen.py
-rw-r--r--    1 daniel.huckmann  admin   8.2M Jan 31 15:58 wordlist.sqlite
```

Copying the `dotted` folder from the repository into `/usr/local/lib/python3.10/site-packages/oktacli` corrected the issue.

**Comment by flypenguin** [comment]
that is extremely weird, but you are absolutely right – dotted is not in the wheel. should be fixed with v18.0.1, please try to upgrade and tell me the results. i'll close it for now cause i just uploaded a version which contains `dotted`. just re-open if i f*cked up (again) 😬

**Comment by dhuckmann** [comment]
Upgraded to `18.0.1` and everything works as expected.

Danke schön. 🤘🏻

**Comment by sanitybit** [comment]
Upgraded to 18.0.1 and everything works as expected.

Danke schön. 🤘🏻

**Comment by flypenguin** [comment]
aber sehr gern :))
