### ISSUE TITLE
csv bug

### ISSUE THREAD

**Issue by gabrielsroka** [flypenguin/okta-cli#20]
csv crashes when there's only 1 column. i think i figured out the format, but it's not well-documented -- examples would be nice.

**Comment by flypenguin** [comment]
I need more information – you mean "bulk update"?

**Comment by gabrielsroka** [comment]
i guess so. it's been 2 months since i used it :)

see also https://github.com/flypenguin/okta-cli/issues/15

**Comment by gabrielsroka** [comment]
it looks like i added trailing commas so it would be 2 columns. note the name of the file

![image](https://github.com/flypenguin/okta-cli/assets/14354736/fb7007a9-8845-4d81-88f3-73fd0d74df0d)

**Comment by flypenguin** [comment]
yah trailing commas are evil – this will not do.

**Comment by gabrielsroka** [comment]
yup. that's the bug.

if i take out the commas, it crashes cuz it can't figure out the csv delimiter

![image](https://github.com/flypenguin/okta-cli/assets/14354736/891cd851-d787-45c6-adac-831a7ee929f1)

**Comment by flypenguin** [comment]
> a csv has 1 or more columns. i don't see why 1 is any worse than 2 or more

well, there's that issue with the missing delimiter ... .

> https://datatracker.ietf.org/doc/html/rfc4180#page-3

🙄  as said ...

> if i add dummy to the header, but not to the records itself, i get

could you provide examles? I just used it extensively to test the new `bulk-add`, and it works basically flawlessly. i have no clue what you're doing, and you keep constructing edge cases. i mean that's fine, it's just hard to debug without precise examples and information about your actual use cases.

also, what do the errors say? maybe try v18.1.0 and give me some feedback, i also increased the error verbosity in the error log files (which you may also post excerpts of, so I know what is happening).

**Comment by gabrielsroka** [comment]
```
~/TryOktaCli$ cat bulk.csv 
id,
00u8nfd32zPIzkTkV5d7,
~/TryOktaCli$ 
~/TryOktaCli$ okta-cli users bulk-update --set profile.department="New IT" bulk.csv 
Bulk update might take a while. Please be patient.
1 - done.
   1 ok     - okta-bulk-update-20240116_203040-ok.json
   0 errors
1 total
~/TryOktaCli$ cp bulk.csv badbulk.csv
~/TryOktaCli$ cat badbulk.csv 
id
00u8nfd32zPIzkTkV5d7
~/TryOktaCli$ okta-cli users bulk-update --set profile.department="New IT" badbulk.csv 
Bulk update might take a while. Please be patient.
Traceback (most recent call last):
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 126, in wrapper
    rv = func(*args, **kwargs)
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 1447, in users_bulk_update
    runs = {
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 1447, in <dictcomp>
    runs = {
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 1404, in file_reader
    for row in dr:
  File "/home/runner/TryOktaCli/.pythonlibs/lib/python3.10/site-packages/oktacli/cli.py", line 1386, in csv_reader
    dialect = csv.Sniffer().sniff(infile.read(4096))
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter


*****************************************************************************
CRITICAL_ERROR: <class '_csv.Error'>

Please report at the issues page with details of what you did. Thank you!
-> https://git.io/JJYqi
*****************************************************************************
```

**Comment by gabrielsroka** [comment]
i referred to bulk-update above, not bulk-add

i also pasted the errors above (scroll up). i'm always editing comments, so perhaps u saw the old version.

these are not edge cases -- u just haven't tested them. they're perfectly valid.

**Comment by gabrielsroka** [comment]
i upgraded, but now it won't run

```
Successfully installed okta-cli-18.1.0
~/TryOktaCli$ okta-cli version
Traceback (most recent call last):
  File "/home/runner/TryOktaCli/.pythonlibs/bin/okta-cli", line 5, in <module>
    from oktacli import cli_main
ModuleNotFoundError: No module named 'oktacli'
```

**Comment by flypenguin** [comment]
> these are not edge cases -- u just haven't tested them. they're perfectly valid, per the rfc.

well, then congrats on testing valid edge cases ... 

> ~/TryOktaCli$ cat bulk.csv 
> id,
> 00u8nfd32zPIzkTkV5d7,
> ~/TryOktaCli$ 
> ~/TryOktaCli$ okta-cli users bulk-update --set profile.department="New IT" bulk.csv 
> Bulk update might take a while. Please be patient.
> 1 - done.
>    1 ok     - okta-bulk-update-20240116_203040-ok.json
>    0 errors
> 1 total

so this _works_ now?

> i upgraded, but now it won't run. i even tried it on another machine

arrrr, yes, my bad. i had to update the whole build setup recently, still reverberates. :/ try again, 18.1.1 should fix it.

**Comment by gabrielsroka** [comment]
bulk.csv works because it has commas. badbulk.csv doesn't work because it lacks commas

**Comment by flypenguin** [comment]
ah! so ... perfect :) . I'll add that to the readme.

**Comment by gabrielsroka** [comment]
since Sniffer().sniff can raise an Error, i'd recommend wrapping the call in a try/except. then u can tell the user that a csv has to have at least 2 columns (going against the rfc).

or try with `dialect='excel'`, which is the default for csv.DictReader.

https://docs.python.org/3/library/csv.html?highlight=csv#csv.Error

so maybe instead of https://github.com/flypenguin/okta-cli/blob/907668803c5b7ae70f2dff3b81930cc5d604a096/src/oktacli/cli.py#L354-L361

try
```py
def csv_reader(filename):
    with open(filename, "r", encoding="utf-8") as infile:
        try:
            dialect = csv.Sniffer().sniff(infile.read(4096))
        except csv.Error as e:
            # sniff will raise an Error if the csv has only 1 column (though it's ok with RFC 4180)
            dialect = 'excel'
        infile.seek(0)
        dr = csv.DictReader(infile, dialect=dialect)
        for row in dr:
            if any(row.values()):
                yield row
```
